# LogWatcher Configuration

# List of logs to watch
logs:
  - path: /var/log/syslog
    name: system
  - path: /var/log/auth.log
    name: auth
  # Add more logs as needed
  # - path: /path/to/your/app.log
  #   name: myapp

# Error patterns to match (regex patterns)
patterns:
  error: error|fail(ed|ure)
  exception: exception
  fatal: fatal
  warning: warning
  critical: critical
